networks:
  net-paste-s7:
    name: net-paste-s7

services:
  php-paste-s7:
    build: ./docker/images/php
    container_name: php-paste-s7
    user: 1000:1000
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache
      PHP_IDE_CONFIG: "serverName=docker"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/runtime/composer-cache:/tmp/composer-cache
      - ./docker/runtime/composer:/.composer
    networks:
      - net-paste-s7
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql-paste-s7:
    container_name: mysql8-paste-s7
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    volumes:
      - ./docker/runtime/mysql-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_USER=paste-s7
      - MYSQL_PASSWORD=paste-s7
      - MYSQL_ROOT_PASSWORD=paste-s7
      - MYSQL_DATABASE=paste-s7
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - net-paste-s7
